### ISSUE TITLE
運営者ページのプラスマークと石川さんの文言修正

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#123]
プラスマークいらないのと、先日言った文言修正ですね。

https://gslab5slack.slack.com/archives/GB7D0QE2E/p1538125985000100
https://gslab5slack.slack.com/archives/GB7D0QE2E/p1537894437000100

**Comment by Ishikawahiroki** [comment]
後、裏返った時長くて重なるバグ

**Comment by Ishikawahiroki** [comment]
一旦完了。みんなのメッセージ入れてみて調整必要なら調整。
