### ISSUE TITLE
検索したときに、検索結果までが遠い

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#136]
<img width="1319" alt="2018-09-29 09 50 35" src="https://user-images.githubusercontent.com/38402160/46240097-6422ef80-c3dd-11e8-8807-2062cbaa8ea9.png">

検索窓から、タイルまでが遠いすね、重要なお知らせっていまだけ表示ですか？

**Comment by Ishikawahiroki** [comment]
重要なお知らせは今だけ表示で、リリース後に下に移動します！

**Comment by B106827** [comment]
完了
