### ISSUE TITLE
トップ画像修正できますか？

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#140]
<img width="206" alt="2018-09-29 12 32 24" src="https://user-images.githubusercontent.com/38402160/46240535-29708580-c3e4-11e8-97e0-9cb07784b0f5.png">

phpのこれはおそらく存在しないのと、
phpは閉じタグ非推奨なんで、できればマストで修正して頂きたいです
プログラミングのサービスなんで、信用に関わります

**Comment by Ishikawahiroki** [comment]
完了。他にあったら言って〜
てか、トップ画像の文言も仮で入れてたけど、変えたほうがいいのかも。。
