### ISSUE TITLE
ここの文言に違和感

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#142]
<img width="468" alt="2018-09-29 12 41 35" src="https://user-images.githubusercontent.com/38402160/46240608-32ae2200-c3e5-11e8-9b26-c6b61bf70501.png">
プログラミングしかいないし（現状）

長い気がします

授業一覧とかではどうですか？

**Comment by Ishikawahiroki** [comment]
ここはhタグでプログラミングを増やしたくて、意図的に今の状態だけどどうだろう。
できればこれでいきたい感じ。

**Comment by B106827** [comment]
保留
