### ISSUE TITLE
バグ　プロフィール編集で、名前押してエンターキーで発動

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#144]
絶対なくしましょう。。悲しいです。。

プロフィール編集で、名前押してエンターキーで発動
<img width="1096" alt="2018-09-29 13 06 20" src="https://user-images.githubusercontent.com/38402160/46240849-b3225200-c3e8-11e8-8084-9cd512cc2366.png">

**Comment by B106827** [comment]
完了
