### ISSUE TITLE
ボタンの色統一

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#147]
<img width="595" alt="2018-09-29 13 15 55" src="https://user-images.githubusercontent.com/38402160/46240995-bc142300-c3ea-11e8-9955-205ebca3e52e.png">
<img width="604" alt="2018-09-29 13 22 07" src="https://user-images.githubusercontent.com/38402160/46241002-d221e380-c3ea-11e8-98ce-9a636eba7dfe.png">
<img width="1380" alt="2018-09-29 10 06 04" src="https://user-images.githubusercontent.com/38402160/46241009-11503480-c3eb-11e8-895d-91ed504e9255.png">

**Comment by Ishikawahiroki** [comment]
先生と生徒でボタン色分けようと思ってやってみたけど変？っぽくなったので一緒にした。
