### ISSUE TITLE
404ページ

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#152]
工数はわからないです

**Comment by Ishikawahiroki** [comment]
memo
htaccessで試したけどできないっぽいか？？
となると処理をよしなに書いていくことになるけど、バリデーションエラーにも影響してくるっぽくてそれだと工数かかりそう。

他軽めのイシュー片付けてから戻る感じで。お客さん側のオープンまではなんとか。

**Comment by Ishikawahiroki** [comment]
一旦はok
