### ISSUE TITLE
カード崩れ

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#171]
<img width="338" alt="2018-10-01 17 18 46" src="https://user-images.githubusercontent.com/38402160/46277453-23be9f80-c59e-11e8-9a0c-61a77893c569.png">

**Comment by mochizuki-pg** [comment]
了解です、前の名残か

**Comment by Ishikawahiroki** [comment]
まだ崩れるパターンあるくさいので、復活させます。
それと、今の場合だとタイトル一行の場合に浮いちゃうな。

**Comment by Ishikawahiroki** [comment]
バグは一旦大丈夫かな...
カードのデザインは改善余地ありね。いずれにしても。
