### ISSUE TITLE
マイページ。本人確認の注意喚起を出し分ける（消えるようにする）

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#179]
<img width="1360" alt="screen shot 2018-10-01 at 22 59 57" src="https://user-images.githubusercontent.com/25481381/46293235-d2c69f80-c5cd-11e8-91f5-e7b9ad0537fa.png">

リリース後でもいいんだけどお願いできる？
本人確認しても今出てる状態。
まあ一度目に入れば問題ないだろうから、paymentsテーブルのstatusが「購入済み」なら、
とかのifでいいよ。簡単に。

**Comment by Ishikawahiroki** [comment]
あ、間違えた。それよりその人のpaymentレコードが存在したら、の方がいいかも。任せるわ

**Comment by B106827** [comment]
決済が2回以上発生していたら非表示に変更

**Comment by B106827** [comment]
完了
