### ISSUE TITLE
通知

### ISSUE THREAD

**Issue by B106827** [teamlaravel/LeLabo#20]

**Comment by Ishikawahiroki** [comment]
めも。
・twitterみたいな通知タイムラインにするのは面倒っぽいし、そこまでいらない。
・mentaみたいなので十分

仕様
・ヘッダ右上にnoticeマーク出しておいて新着あればピコンと出す。
　タイミング
　①チャットで新着がきた場合（つまりfirebaseと関わってくるのか！？）
　②出金申請したのちに、入金が完了した場合


浅海CTOと相談。
