### ISSUE TITLE
[議論] 会員登録をしていないユーザーが先生になるボタンを押したときの導線

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#246]
現状、先生になるボタンを押すと、無条件でログインに飛ばされる

ログインと、新規登録ボタンを2つ並べて、クリックした先に飛ばすとかどうですか？

**Comment by Ishikawahiroki** [comment]
ログインと、新規登録ボタンを2つ並べて、クリックした先に飛ばすでも良いsし、

それか、ログインページに「新規登録がまだの方はこちら」をつけるかー。どっちかで対応！

**Comment by B106827** [comment]
ログイン画面に「会員登録がまだの方はこちら」追加
