### ISSUE TITLE
【議論】TOPの対象者だけ...じゃなくて全部出したい。

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#252]
全部出しても2行で治るだろうし、順番的に高校生が出ないパターンが多いので、出したいな〜と。
どうスカCTO？お手隙で。
ちなみに、うちのお客さん小学生・中学生・高校生どこに一番刺さるのかはまだ見えていない。

**Comment by B106827** [comment]
完了
