### ISSUE TITLE
【議論】カードのタイトルの見せ方を変更する

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#279]
僕の周りでサイトの感想を聞いてみた。
非エンジニアの感想として、
「素人目だとhtmlとか言われても何ができるかよくわからん」
が圧倒的に多い。カードのタイトルに分からない言語がいくつも登場する時点で「？」が出る。
やっぱそうかという感じ。おそらくだが、ここが今一番のハードルになってると思われる。

もっと一般人でもわかるように、
例えばだが「ゲームを作る/ webサイトを作る/...」などの表現で目的別にあって、先生が並んでいたらわかりやすいのではないか的な意見。まじでその通りと思った。
今の機能を利用して少ない工数でできる変更を検討する。これ早急に。

**Comment by B106827** [comment]
カテゴリ登録機能実装完了
