### ISSUE TITLE
キーワード検索機能

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#299]
もし可能であればお手隙でお願いします。

**Comment by Ishikawahiroki** [comment]
デザインは考え中です
【仕様】
・トップページにあれば良いです。
・検索キーワードが、とにかくlessonテーブルのいずれかのカラムに含まれていれば、その授業を表示させる。
・現ララボのand検索の中に入れてもらえると助かるかも（キーワードでもand検索できる状態）

**Comment by B106827** [comment]
完了。
・授業タイトル
・授業内容
・先生の名前
・場所(県or都市)
・カテゴリ
・タグ
・対象者
のどれかで、テキスト部分一致検索で設定。
また、カテゴリ検索もand検索にした。

※フリーワード検索ではなぜかdisplay_flg=1等の絞り込みが無視されるバグが残っています

**Comment by B106827** [comment]
アノテーションコメント追記しました！

**Comment by B106827** [comment]
バグ修正完了
