### ISSUE TITLE
ステータス表示

### ISSUE THREAD

**Issue by B106827** [teamlaravel/LeLabo#302]
「受付中」「非表示」「今忙しい」

**Comment by Ishikawahiroki** [comment]
デザインは考え中です。
【仕様】
・授業を出品すると、ステータスはデフォルトで「受付中」となる
・マイページから「受付中」「今忙しい」「非表示」の３段階変更できる
（もちろん複数授業出してる人は、それぞれの授業で変更できる）
・受付中->表示
・今忙しい->表示するがメッセージは送れない状態
・非表示->非表示
・授業詳細ページのどこかに「受付中」or「今忙しい」ステータスが表示されている

**Comment by B106827** [comment]
完了。
授業出品時デフォルトで「受付中」のdisplay_flg=1がインサートされる。
変更はマイページから可能。「受付中」「今忙しい」「非表示」の３段階変更できる。
display_flgはそれぞれ1,2,3の値を割り当てている。

授業詳細ページのに「受付中」or「今忙しい」ステータスが表示されている。
今忙しいステータスの場合はメッセージは送れない。「現在受付停止中」の表示に。
