### ISSUE TITLE
【新デザイン】授業登録時のデフォルト写真を選べるにしたい

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#303]
添付参考。授業登録時にこんな感じでデフォルト写真を数パターンのうちから一つ選べる機能も追加したいな。
<img width="677" alt="2018-11-15 11 53 22" src="https://user-images.githubusercontent.com/25481381/48527139-7b566780-e8cd-11e8-95a5-2cef63e24d30.png">

**Comment by B106827** [comment]
機能周りは完了
