### ISSUE TITLE
バリデーション確認(一旦授業編集ページと返金申請ページは置いておく)

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#320]
ajaxに変えなきゃいけないかもしれない。あとで戻ってやります。
fixme記述ずみ。

**Comment by B106827** [comment]
・ログイン
・授業出品
・プロフィール編集
・お問い合わせ

**Comment by Ishikawahiroki** [comment]
・ログイン、新規会員登録→取り掛かります。モーダルなのでajax使えばいいのかな
