### ISSUE TITLE
footerにtwitter埋め込む

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#334]

**Comment by B106827** [comment]
・twitterアカウント
LeLabo_official
teamlaravel

**Comment by Ishikawahiroki** [comment]
ツイッターのウィジットだと不自然になるので、テンプレに用意されてるpluginを使用。
但し、「Posted 14 seconds ago」の部分だけ日本語化できず。
該当箇所：<p class="timePosted">の部分だがどこで制御されているかいまいちわからない。

この一文だけなので、最悪このままでも良いができれば対応。
