### ISSUE TITLE
【レスポンシブ】ログイン後のヘッダーメニューの崩れ

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#411]
石川対応します。

**Comment by B106827** [comment]
トップページ以外で文字サイズが違っていたのは直接font-size指定しました。あと、トップページ以外では、メニューaタグにhover時underlineあったので殺しときました！

**Comment by Ishikawahiroki** [comment]
テンプレでは、ログイン後のメニューが画面右上に出て邪魔なので、
ハンバーガーの中に入れ込みました。
