### ISSUE TITLE
授業詳細ページの各種ボタンが見えない

### ISSUE THREAD

**Issue by mochizuki-pg** [teamlaravel/LeLabo#452]
授業詳細がタイトルの長さに依存して、ボタンが下の方に行ってるのと
ボタンが白字のため、見えなくなっている

<img width="738" alt="2019-01-29 17 09 02" src="https://user-images.githubusercontent.com/38402160/51893551-9a529900-23e8-11e9-8d06-2e9e72c7a667.png">

**Comment by Ishikawahiroki** [comment]
時間ない中ありがとう！じゃんじゃんイシュー歓迎
これはバリデーションの確認と一緒にやななきゃあかん奴ですね。一通り。

これ石川対応〜

重めのイシューが解消できず進まん...
俺も全体まだ見れてないー

**Comment by Ishikawahiroki** [comment]
す、すまん。
もう今は、タイトル35文字以内にバリデーション変更してたから今は大丈夫なんでした。
そんなに文字数入れられないはず。

送ったsqlデータ吸い込んでもらってせいだと思うけど、テスト途中のデータも混じってるからバリデーション条件と整合してないデータ混じってる。申し訳ない！
