### ISSUE TITLE
TOPページのデザインを整える

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamlaravel/LeLabo#8]
手が空いてる人からやって行きましょう。
やる前にここで宣言してからお願いします。

**Comment by Ishikawahiroki** [comment]
とりあえず
・ヘッダーとフッターいじります。

**Comment by Ishikawahiroki** [comment]
・ヘッダーはとりあえずだけど整えた。

ヘッダー以降は引き続き作業します。
（手空いてたら自由に入ってもらってもokです）

**Comment by B106827** [comment]
今トップちょっといじってます。
