### ISSUE TITLE
バリデーションメッセージ確認

### ISSUE THREAD

**Issue by B106827** [teamlaravel/LeLabo#87]

**Comment by B106827** [comment]
ajax以外のバリデーション箇所のメッセージが日本語化できていない

**Comment by B106827** [comment]
バリデーション全チェック

**Comment by B106827** [comment]
授業編集、プロフィール編集参照

**Comment by Ishikawahiroki** [comment]
・パスワード間違えた時のメッセージ変だわ

あとでまとめて全部チェックします

**Comment by Ishikawahiroki** [comment]
全部チェック済み。
今後の課題。
・フィードバック送信はバリデーション 効いてるけど、モーダルなのでエラー文表示ならない。面倒なので後回し。
・ブラウザについてるバリデーション が出るのは仕方ない。
